### ISSUE TITLE
当没有好感数据时执行好感排行指令出现问题

### ISSUE THREAD

**Issue by LemonNek0** [Travellerrr/Favorability#2]
2024-12-24 01:44:18 V/Bot.3`*****`4: [test2(17`******`1)] 不学安全还怎么当猫(245`******`2) -> #好感度排行
2024-12-24 01:44:18 I/onebot-mirai: 广播反向websocket事件, 共发送 :1
2024-12-24 01:44:18 I/OneBotWsClient: 收到原始消息： {"status":"failed","retcode":1404,"data":null,"message":"不支持的API undefined","wording":"不支持的API undefined","echo":null}

**Comment by Echomirix** [comment]
好感度排行指令是转发消息，一般情况可以发出，能否提供更详细的内容？

**Comment by LemonNek0** [comment]
```
2024-12-29 22:29:03 D/Onebot: [Recv] <-- {"self_id":2756912656,"user_id":2452973892,"time":1735482543,"message_id":1267665159,"message_seq":1267665159,"real_id":1267665159,"message_type":"group","sender":{"user_id":2452973892,"nickname":"不学安全还怎么当猫","card":"","role":"owner"},"raw_message":"/好感排行","font":14,"sub_type":"normal","message":[{"type":"text","data":{"text":"/好感排行"}}],"message_format":"array","post_type":"message","group_id":177072571}
2024-12-29 22:29:04 D/Onebot: [Send] --> {"action":"send_group_forward_msg","params":{"group_id":177072571,"messages":[]},"echo":12}
2024-12-29 22:29:04 D/Onebot: [Recv] <-- {"status":"failed","retcode":1200,"data":null,"message":"消息体无法解析, 请检查是否发送了不支持的消息类型","wording":"消息体无法解析, 请检查是否发送了不支持的消息类型","echo":12}
2024-12-29 22:29:04 W/Onebot: 请求失败: [send_group_forward_msg] 请求失败: app=NapCat.Onebot v4.2.40, message=消息体无法解析, 请检查是否发送了不支持的消息类型, retJson={"status":"failed","retcode":1200,"data":null,"message":"消息体无法解析, 请检查是否发送了不支持的消息类型","wording":"消息体无法解析, 请检查是否发送了不支持的消息类型","echo":12}。如果你认为这是 Overflow 的问题，请带上 logs/onebot 中的日志来反馈。
2024-12-29 22:29:04 V/Onebot: Stacktrace: 
cn.evolvefield.onebot.client.util.ActionFailedException: 请求失败: app=NapCat.Onebot v4.2.40, message=消息体无法解析, 请检查是否发送了不支持的消息类型, retJson={"status":"failed","retcode":1200,"data":null,"message":"消息体无法解析, 请检查是否发送了不支持的消息类型","wording":"消息体无法解析, 请检查是否发送了不支持的消息类型","echo":12}
	at cn.evolvefield.onebot.client.util.ActionSendRequest.send(ActionSendRequest.kt:67)
	at cn.evolvefield.onebot.client.util.ActionSendRequest$send$1.invokeSuspend(ActionSendRequest.kt)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.internal.ScopeCoroutine.afterResume(Scopes.kt:33)
	at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.kt:102)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
	at kotlinx.coroutines.DispatchedTaskKt.resume(DispatchedTask.kt:178)
	at kotlinx.coroutines.DispatchedTaskKt.dispatch(DispatchedTask.kt:166)
	at kotlinx.coroutines.CancellableContinuationImpl.dispatchResume(CancellableContinuationImpl.kt:397)
	at kotlinx.coroutines.CancellableContinuationImpl.resumeImpl(CancellableContinuationImpl.kt:431)
	at kotlinx.coroutines.CancellableContinuationImpl.resumeImpl$default(CancellableContinuationImpl.kt:420)
	at kotlinx.coroutines.CancellableContinuationImpl.resumeWith(CancellableContinuationImpl.kt:328)
	at kotlinx.coroutines.ResumeAwaitOnCompletion.invoke(JobSupport.kt:1413)
	at kotlinx.coroutines.JobSupport.completeStateFinalization(JobSupport.kt:318)
	at kotlinx.coroutines.JobSupport.tryFinalizeSimpleState(JobSupport.kt:295)
	at kotlinx.coroutines.JobSupport.tryMakeCompleting(JobSupport.kt:856)
	at kotlinx.coroutines.JobSupport.makeCompleting$kotlinx_coroutines_core(JobSupport.kt:806)
	at kotlinx.coroutines.CompletableDeferredImpl.complete(CompletableDeferred.kt:92)
	at cn.evolvefield.onebot.client.util.ActionSendRequest.onCallback(ActionSendRequest.kt:80)
	at cn.evolvefield.onebot.client.handler.ActionHandler.onReceiveActionResp(ActionHandler.kt:41)
	at cn.evolvefield.onebot.client.connection.IAdapter$DefaultImpls.onReceiveMessage(IAdapter.kt:27)
	at cn.evolvefield.onebot.client.connection.WSClient.onReceiveMessage(WSClient.kt:19)
	at cn.evolvefield.onebot.client.connection.WSClient.onMessage(WSClient.kt:68)
	at top.mrxiaom.overflow.internal.deps.websocket.client.WebSocketClient.onWebsocketMessage(WebSocketClient.java:661)
	at top.mrxiaom.overflow.internal.deps.websocket.drafts.Draft_6455.processFrameText(Draft_6455.java:986)
	at top.mrxiaom.overflow.internal.deps.websocket.drafts.Draft_6455.processFrame(Draft_6455.java:910)
	at top.mrxiaom.overflow.internal.deps.websocket.WebSocketImpl.decodeFrames(WebSocketImpl.java:397)
	at top.mrxiaom.overflow.internal.deps.websocket.WebSocketImpl.decode(WebSocketImpl.java:229)
	at top.mrxiaom.overflow.internal.deps.websocket.client.WebSocketClient.run(WebSocketClient.java:544)
	at java.base/java.lang.Thread.run(Thread.java:1583)


```
以上为网络日志
![image](https://github.com/user-attachments/assets/4be7323a-d3cd-425f-9231-368d967c8754)

**Comment by LemonNek0** [comment]
偶发现象，无法复现

**Comment by Echomirix** [comment]
貌似因为数据库/群聊中没有用户导致的聊天记录为空，[6234c42](https://github.com/Travellerrr/Favorability/commit/6234c421e1ecdb87d6eafe541f838051f3df4cc6)已修复
